stages:
  - test
  - delivery

test_job:
  stage: test
  script:
    - docker compose -f DropSpace/tests/docker-compose.yml down
    - docker compose -f DropSpace/tests/docker-compose.yml up --build
    - docker compose -f DropSpace/tests/docker-compose.yml up

deploy_job:
  stage: delivery
  only:
    - master
  script:
    - docker login -p $DOCKER_REGISTRY_KEY -u "$DOCKER_REGISTRY_USER"
    - docker tag dropcontainer:test $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
