image: docker:24.0.2

services:
  - docker:24.0.2-dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - delivery

test_job:
  stage: test
  script:
    - docker compose -f DropSpace/tests/docker-compose.yml down
    - docker compose -f DropSpace/tests/docker-compose.yml build dropcontainer
    - docker compose -f DropSpace/tests/docker-compose.yml up

deploy_job:
  stage: delivery
  only:
    - master
  script:
    - docker login -p $DOCKER_REGISTRY_KEY -u "$DOCKER_REGISTRY_USER"
    - docker tag dropcontainer:test $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE
