version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: DropSpace/Dockerfile
    networks:
      - webnet
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet

networks:
  webnet:
