name: dropspace-ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: dropspace
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: >-
          --mount type=volume,source=postgres_data,target=/var/lib/postgresql/data

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          for i in {1..30}; do
            if nc -z localhost 5432; then
              echo "PostgreSQL is up!"
              break
            fi
            echo "PostgreSQL is unavailable - sleeping"
            sleep 1
          done

      - name: Build frontend Docker image
        run: |
          docker build -t my-frontend-image:latest -f Dockerfile.frontend .

      - name: Build backend Docker image
        run: |
          docker build -t my-backend-image:latest -f Dockerfile.backend .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Mock test step
        run: |
          echo "Running mock tests for frontend..."
          echo "Running mock tests for backend..."

  # push:
  #   runs-on: ubuntu-latest
  #   needs: [build, test]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Push images to Docker Hub
  #       run: |
  #         echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
  #         docker tag my-frontend-image ${{ secrets.DOCKER_USERNAME }}/dropspace-frontend:latest
  #         docker tag my-backend-image ${{ secrets.DOCKER_USERNAME }}/dropspace-backend:latest
  #         docker push ${{ secrets.DOCKER_USERNAME }}/dropspace-frontend:latest
  #         docker push ${{ secrets.DOCKER_USERNAME }}/dropspace-backend:latest